version: '3.10'

services:
    app:
        build: ./
        command: streamlit run image_detection.py --server.port 8501
        volumes:
            - ./:/usr/src/app
        ports:
            - 8501:8501
        image: dramb/automl:latest